### PR TITLE
Add method to load game from RAM

### PR DESCRIPTION
**Pull request by tytydraco**
This allows us to load games directly from a ByteArray, which is very
much ideal when bundling game files in the assets directory of the app.
Since assets cannot be accessed directly, they must be first copied out
of the app. We can avoid this by loading the game directly from a
ByteArray.

It is understandable if you do not want to merge this change into the main repo since it would require devs to explicitly specify `null` to the gameFileBytes parameter. Let me know your thoughts.

### CODE REVIEW

**Review by Swordfish90 — CHANGES_REQUESTED** [review]
Not a problem at all taking it upstream. Can you put it into a separate constructor? This way we can avoid the passing null for one of them.

**Comment by tytydraco** [comment]
Updated. The approach is kind of messy because of how the initialization already works, but let me know your thoughts. Of course, I wouldn't mind changing it to a more appropriate solution if you want. 

I think in the future it may be beneficial to make the coreFilePath and gameFilePath components nullable and then expose the private variables for adjustment, finalized with an `init()` or `create()` method that replaces the `init {}` call. That way, the late configuration can be made before the GLRetroView is initialized, and the constructors will be way cleaner.

**Comment by Swordfish90** [comment]
Yeah, I agree. The constructor is starting to be quite huge, maybe it would be better to have a configuration data class to conveniently pass the (many) configuration parameters.

For now, it is enough if you fix the merge issue and I'll take this upstream.

Thank you again for the many contributions! :smile:

**Comment by tytydraco** [comment]
Fixed the conflict. And you're welcome! 👍

**Comment by Swordfish90** [comment]
Looks good. Thank you @tytydraco

**Pull request merged**
